// Spiritual gifts
export const giftQuestionMap = {
  A: "Leadership",
  B: "Administration",
  C: "Teaching",
  D: "Knowledge",
  E: "Wisdom",
  F: "Prophecy",
  G: "Discernment",
  H: "Exhortation",
  I: "Shepherding",
  J: "Faith",
  K: "Evangelism",
  L: "Apostleship",
  M: "Service/Helps",
  N: "Mercy",
  O: "Giving",
  P: "Hospitality",
  Q: "Intercession",
  R: "Craftsmanship",
  S: "Music/Worship",
  T: "Missions",
  U: "Healing",
  V: "Deliverance",
  W: "Interpretation",
  X: "Tongues",
};
