// Spiritual gifts
export const giftQuestionMap = {
  A: "Administration",
  B: "Apostleship",
  C: "Craftsmanship",
  D: "Discernment",
  E: "Evangelism",
  F: "Exhortation",
  G: "Faith",
  H: "Giving",
  I: "Healing",
  J: "Helps",
  K: "Hospitality",
  L: "Intercession",
  M: "Knowledge",
  N: "Leadership",
  O: "Mercy",
  P: "Miracles",
  Q: "Missionary",
  R: "Music/Worship",
  S: "Pastor/Shepherd",
  T: "Prophecy",
  U: "Service",
  V: "Teaching",
  W: "Tongues & Interpretation",
  X: "Wisdom",
};
